mock: false
lightpin: 19
buttonpin: 4

# Set to -1 for no zerocross
zerocrosspin: 5

rest:
    enabled: false
    port: 5445

mqtt:
    enabled: true
    broker: raspberrypi.local:1883
    prefix: sunrise
    clientid: sunrise
